name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.0
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors --force
      - run: mix credo --strict
      - run: mix test
